### ISSUE TITLE
chrome browser issue linux

### ISSUE THREAD

**Issue by ngmisl** [farizrahman4u/loopgpt#10]
In AutoGPT it's fixed by setting the browser to firefox... are there any settings for this in the module?

**Comment by FayazRahman** [comment]
Hey @ngmisl, we will add fallback to firefox

**Comment by FayazRahman** [comment]
@ngmisl We have added Firefox supported and merged it to main. We'll release it soon!

**Comment by FayazRahman** [comment]
@ngmisl We have released Firefox support, hoping it fixes your issue!
