### ISSUE TITLE
Function call `agent.config()` throws an error if `agent.clear_state()` is called before it

### ISSUE THREAD

**Issue by iskandarreza** [farizrahman4u/loopgpt#41]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/farizrahman4u/LoopGPT/labels/bug) didn't find any similar reports.

### Expected Behavior

It shouldn't cause an error

### Current behaviour

It throws the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\GitHub\loopgpt\loopgpt\agent.py", line 441, in config
    "progress": self.progress[:],
TypeError: 'NoneType' object is not subscriptable
```

### Steps to reproduce

```python
import loopgpt

agent = loopgpt.Agent()
agent.name = "Node Exec Test"
agent.goals = "Run the list_files command and then the list_agents command"
agent_init_config = agent.config() # save init config

agent.clear_state() # start fresh
agent.from_config(agent_init_config) # reload cleared config
print(agent.config()) # 💀💀
```

### Possible solution

Update line 346 in `agent.py` to this:

```py
self.progress = []
```

[Compare](https://github.com/farizrahman4u/loopgpt/compare/main...iskandarreza:loopgpt:fix/config_clear_state_progress_iterable)

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Python Version

- [ ] >= v3.11
- [X] v3.10
- [ ] v3.9
- [ ] <= v3.8

### LoopGPT Version

latest from main branch

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of LoopGPT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by johnwillbolt** [comment]
Python throws the error, "TypeError: 'SomeType' object is not subscriptable," when you attempt to use a bracket `[]` on an object that is not a list or dict, i.e. is not subscriptable. Currently line 346 of agent.py in `clear_state()` is,
```
346: self.progress = None
```
The error, "TypeError: 'NoneType' object is not subscriptable," is thrown on line 441 of agent.py in `config()`,
```
441: "progress": self.progress[:],
```
Switching line 346 to `self.progress = []` fixes this, as you found. This is the same value assigned to `self.progress` on line 60 of agent.py in `__init__()`, so it seems like an acceptable solution to me. 

Thinking I will add your example as a test case in test_serde.py as `test_serde_after_clear_state()` and submit a PR. If you feel this test case should go into its own file, please let me know. In general, test coverage is pretty abysmal. It would be good to have a parallel file structure for unit tests and some proper mocking, imo, but that is a separate discussion.

**Comment by FayazRahman** [comment]
Thanks a lot for opening the issue @iskandarreza!
